site_name: JetBot
theme:
    name: "material"
    logo: images/logo.png
    favicon: images/favicon.png
    font: Incosolata
    palette:
        scheme: nvgreen 
    features:
       - navigation.expand

repo_url: https://github.com/NVIDIA-AI-IOT/jetbot

plugins:
  - search
use_directory_urls: false

edit_uri: blob/master/docs
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.highlight:
        use_pygments: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list  # for image sizes https://github.com/mkdocs/mkdocs/issues/1678
# use_directory_urls - False to fix broken raw html image links
# https://github.com/mkdocs/mkdocs/issues/991


nav:

  - Home: index.md
  - Getting Started: getting_started.md
  - Bill of Materials: bill_of_materials.md
  - Hardware Setup: hardware_setup.md
  - Software Setup:
      - Using SD Card Image: software_setup/sd_card.md
      - Using Docker Container: software_setup/docker.md
      - Native setup from scratch (No docker): software_setup/native_setup.md
  - Examples: 
      - Basic Motion: examples/basic_motion.md
      - Teleoperation: examples/teleoperation.md
      - Collision Avoidance: examples/collision_avoidance.md
      - Road Following: examples/road_following.md
      - Object Following: examples/object_following.md
      - Community Examples: examples/community_examples.md
  - Reference:
      - Third Party Kits: third_party_kits.md
      - 3D Printing: 3d_printing.md
      - Contributing: CONTRIBUTING.md
      - Changes: CHANGELOG.md
      - Wi-Fi setup: software_setup/wifi_setup.md
      - Docker Tips: reference/docker_tips.md

extra_css:
  - css/version-select.css
  - css/colors.css

extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: G-Z68BPY8NZV
